[package]
name = "chip8"
version = "0.1.0"
authors = ["Protoshark <protoshark@pm.me>"]
edition = "2018"

[features]
default = []
sdl = ["sdl2"]

[dependencies]
sdl2 = { version = "0.34", optional = true }
rand = "0.8"
